from constants import url, ca
from media import index as media

X7D = {
        "eth": (
            "(ETH)",
            url.ETHER_ADDRESS,
            "eth",    
        ),
        "arb": (
            "(ARB)",
            url.ARB_ADDRESS,
            "eth",
        ),
        "poly": (
            "(POLYGON)",
            url.POLY_ADDRESS,
            "matic",
        ),
        "bsc": (
            "(BSC)",
            url.BSC_ADDRESS,
            "bnb",
        ),
        "opti": (
            "(OPTI)",
            url.OPTI_ADDRESS,
            "eth",
        ),
        "base": (
            "(BASE)",
            url.BASE_ADDRESS,
            "eth",
        ),
    }


X7DAO = {
        "eth": (
            "(ETH)",
            url.ETHER_TOKEN,
            url.DEX_TOOLS_ETH,
            ca.X7DAO_PAIR_ETH,
            url.XCHANGE_BUY_ETH,
            "Etherscan",
            "eth",
        ),
        "arb": (
            "(ARB)",
            url.ARB_TOKEN,
            url.DEX_TOOLS_ARB,
            ca.X7DAO_PAIR_ARB,
            url.XCHANGE_BUY_ARB,
            "Arbscan",
            "eth",
        ),
        "poly": (
            "(POLYGON)",
            url.POLY_TOKEN,
            url.DEX_TOOLS_POLY,
            ca.X7DAO_PAIR_POLY,
            url.XCHANGE_BUY_POLY,
            "Polygonscan",
            "matic",
        ),
        "bsc": (
            "(BSC)",
            url.BSC_TOKEN,
            url.DEX_TOOLS_BSC,
            ca.X7DAO_PAIR_BSC,
            url.XCHANGE_BUY_BSC,
            "BSCscan",
            "bnb",
        ),
        "opti": (
            "(OP)",
            url.OPTI_TOKEN,
            url.DEX_TOOLS_OPTI,
            ca.X7DAO_PAIR_OPTI,
            url.XCHANGE_BUY_OPTI,
            "Optimismscan",
            "eth",
        ),
        "base": (
            "(BASE)",
            url.BASE_TOKEN,
            url.DEX_TOOLS_BASE,
            ca.X7DAO_PAIR_BASE,
            url.XCHANGE_BUY_BASE,
            "Basescan",
            "eth",
        ),
    }


X7R = {
        "eth": (
            "(ETH)",
            url.ETHER_TOKEN,
            url.DEX_TOOLS_ETH,
            ca.X7R_PAIR_ETH,
            url.XCHANGE_BUY_ETH,
            "Etherscan",
            "eth",
        ),
        "arb": (
            "(ARB)",
            url.ARB_TOKEN,
            url.DEX_TOOLS_ARB,
            ca.X7R_PAIR_ARB,
            url.XCHANGE_BUY_ARB,
            "Arbscan",
            "eth",
        ),
        "poly": (
            "(POLYGON)",
            url.POLY_TOKEN,
            url.DEX_TOOLS_POLY,
            ca.X7R_PAIR_POLY,
            url.XCHANGE_BUY_POLY,
            "Polygonscan",
            "matic",
        ),
        "bsc": (
            "(BSC)",
            url.BSC_TOKEN,
            url.DEX_TOOLS_BSC,
            ca.X7R_PAIR_BSC,
            url.XCHANGE_BUY_BSC,
            "BSCscan",
            "bnb",
        ),
        "opti": (
            "(OP)",
            url.OPTI_TOKEN,
            url.DEX_TOOLS_OPTI,
            ca.X7R_PAIR_OPTI,
            url.XCHANGE_BUY_OPTI,
            "Optimismscan",
            "eth",
        ),
        "base": (
            "(BASE)",
            url.BASE_TOKEN,
            url.DEX_TOOLS_BASE,
            ca.X7R_PAIR_BASE,
            url.XCHANGE_BUY_BASE,
            "Basescan",
            "eth",
        ),
    }


X7101 = {
    "eth": (
        "(ETH)",
        url.ETHER_TOKEN,
        url.DEX_TOOLS_ETH,
        ca.X7101_PAIR_ETH,
        url.XCHANGE_BUY_ETH,
        "Etherscan",
        "eth",
    ),
    "arb": (
        "(ARB)",
        url.ARB_TOKEN,
        url.DEX_TOOLS_ARB,
        ca.X7101_PAIR_ARB,
        url.XCHANGE_BUY_ARB,
        "Arbscan",
        "eth",
    ),
    "poly": (
        "(POLYGON)",
        url.POLY_TOKEN,
        url.DEX_TOOLS_POLY,
        ca.X7101_PAIR_POLY,
        url.XCHANGE_BUY_POLY,
        "Polygonscan",
        "matic",
    ),
    "bsc": (
        "(BSC)",
        url.BSC_TOKEN,
        url.DEX_TOOLS_BSC,
        ca.X7101_PAIR_BSC,
        url.XCHANGE_BUY_BSC,
        "BSCscan",
        "bnb",
    ),
    "opti": (
        "(OP)",
        url.OPTI_TOKEN,
        url.DEX_TOOLS_OPTI,
        ca.X7101_PAIR_OPTI,
        url.XCHANGE_BUY_OPTI,
        "Optimismscan",
        "eth",
    ),
    "base": (
        "(BASE)",
        url.BASE_TOKEN,
        url.DEX_TOOLS_BASE,
        ca.X7101_PAIR_BASE,
        url.XCHANGE_BUY_BASE,
        "Basescan",
        "eth",
    ),
}


X7102 = {
        "eth": (
            "(ETH)",
            url.ETHER_TOKEN,
            url.DEX_TOOLS_ETH,
            ca.X7102_PAIR_ETH,
            url.XCHANGE_BUY_ETH,
            "Etherscan",
            "eth",
        ),
        "arb": (
            "(ARB)",
            url.ARB_TOKEN,
            url.DEX_TOOLS_ARB,
            ca.X7102_PAIR_ARB,
            url.XCHANGE_BUY_ARB,
            "Arbscan",
            "eth",
        ),
        "poly": (
            "(POLYGON)",
            url.POLY_TOKEN,
            url.DEX_TOOLS_POLY,
            ca.X7102_PAIR_POLY,
            url.XCHANGE_BUY_POLY,
            "Polygonscan",
            "matic",
        ),
        "bsc": (
            "(BSC)",
            url.BSC_TOKEN,
            url.DEX_TOOLS_BSC,
            ca.X7102_PAIR_BSC,
            url.XCHANGE_BUY_BSC,
            "BSCscan",
            "bnb",
        ),
        "opti": (
            "(OP)",
            url.OPTI_TOKEN,
            url.DEX_TOOLS_OPTI,
            ca.X7102_PAIR_OPTI,
            url.XCHANGE_BUY_OPTI,
            "Optimismscan",
            "eth",
        ),
        "base": (
            "(BASE)",
            url.BASE_TOKEN,
            url.DEX_TOOLS_BASE,
            ca.X7102_PAIR_BASE,
            url.XCHANGE_BUY_BASE,
            "Basescan",
            "eth",
        ),
    }


X7103 = {
        "eth": (
            "(ETH)",
            url.ETHER_TOKEN,
            url.DEX_TOOLS_ETH,
            ca.X7103_PAIR_ETH,
            url.XCHANGE_BUY_ETH,
            "Etherscan",
            "eth",
        ),
        "arb": (
            "(ARB)",
            url.ARB_TOKEN,
            url.DEX_TOOLS_ARB,
            ca.X7103_PAIR_ARB,
            url.XCHANGE_BUY_ARB,
            "Arbscan",
            "eth",
        ),
        "poly": (
            "(POLYGON)",
            url.POLY_TOKEN,
            url.DEX_TOOLS_POLY,
            ca.X7103_PAIR_POLY,
            url.XCHANGE_BUY_POLY,
            "Polygonscan",
            "matic",
        ),
        "bsc": (
            "(BSC)",
            url.BSC_TOKEN,
            url.DEX_TOOLS_BSC,
            ca.X7103_PAIR_BSC,
            url.XCHANGE_BUY_BSC,
            "BSCscan",
            "bnb",
        ),
        "opti": (
            "(OP)",
            url.OPTI_TOKEN,
            url.DEX_TOOLS_OPTI,
            ca.X7103_PAIR_OPTI,
            url.XCHANGE_BUY_OPTI,
            "Optimismscan",
            "eth",
        ),
        "base": (
            "(BASE)",
            url.BASE_TOKEN,
            url.DEX_TOOLS_BASE,
            ca.X7103_PAIR_BASE,
            url.XCHANGE_BUY_BASE,
            "Basescan",
            "eth",
        ),
    }


X7104 = {
        "eth": (
            "(ETH)",
            url.ETHER_TOKEN,
            url.DEX_TOOLS_ETH,
            ca.X7104_PAIR_ETH,
            url.XCHANGE_BUY_ETH,
            "Etherscan",
            "eth",
        ),
        "arb": (
            "(ARB)",
            url.ARB_TOKEN,
            url.DEX_TOOLS_ARB,
            ca.X7104_PAIR_ARB,
            url.XCHANGE_BUY_ARB,
            "Arbscan",
            "eth",
        ),
        "poly": (
            "(POLYGON)",
            url.POLY_TOKEN,
            url.DEX_TOOLS_POLY,
            ca.X7104_PAIR_POLY,
            url.XCHANGE_BUY_POLY,
            "Polygonscan",
            "matic",
        ),
        "bsc": (
            "(BSC)",
            url.BSC_TOKEN,
            url.DEX_TOOLS_BSC,
            ca.X7104_PAIR_BSC,
            url.XCHANGE_BUY_BSC,
            "BSCscan",
            "bnb",
        ),
        "opti": (
            "(OP)",
            url.OPTI_TOKEN,
            url.DEX_TOOLS_OPTI,
            ca.X7104_PAIR_OPTI,
            url.XCHANGE_BUY_OPTI,
            "Optimismscan",
            "eth",
        ),
        "base": (
            "(BASE)",
            url.BASE_TOKEN,
            url.DEX_TOOLS_BASE,
            ca.X7104_PAIR_BASE,
            url.XCHANGE_BUY_BASE,
            "Basescan",
            "eth",
        ),
    }


X7105 = {
        "eth": (
            "(ETH)",
            url.ETHER_TOKEN,
            url.DEX_TOOLS_ETH,
            ca.X7105_PAIR_ETH,
            url.XCHANGE_BUY_ETH,
            "Etherscan",
            "eth",
        ),
        "arb": (
            "(ARB)",
            url.ARB_TOKEN,
            url.DEX_TOOLS_ARB,
            ca.X7105_PAIR_ARB,
            url.XCHANGE_BUY_ARB,
            "Arbscan",
            "eth",
        ),
        "poly": (
            "(POLYGON)",
            url.POLY_TOKEN,
            url.DEX_TOOLS_POLY,
            ca.X7105_PAIR_POLY,
            url.XCHANGE_BUY_POLY,
            "Polygonscan",
            "matic",
        ),
        "bsc": (
            "(BSC)",
            url.BSC_TOKEN,
            url.DEX_TOOLS_BSC,
            ca.X7105_PAIR_BSC,
            url.XCHANGE_BUY_BSC,
            "BSCscan",
            "bnb",
        ),
        "opti": (
            "(OP)",
            url.OPTI_TOKEN,
            url.DEX_TOOLS_OPTI,
            ca.X7105_PAIR_OPTI,
            url.XCHANGE_BUY_OPTI,
            "Optimismscan",
            "eth",
        ),
        "base": (
            "(BASE)",
            url.BASE_TOKEN,
            url.DEX_TOOLS_BASE,
            ca.X7105_PAIR_BASE,
            url.XCHANGE_BUY_BASE,
            "Basescan",
            "eth",
        ),
    }
